### ISSUE TITLE
Consider changing the hostname of master.client.vm

### ISSUE THREAD

**Issue by justin-stephenson** [SSSD/sssd-test-suite#11]
The client hostname is a bit confusing in my opinion, with `master` and `client` in the same name. It should not be confused with an IPA master, removing the word master from the hostname would be preferred.

**Comment by pbrezina** [comment]
I think this can be done. Would you like to open a PR?

**Comment by justin-stephenson** [comment]
Sure, i'll open a PR.

**Comment by justin-stephenson** [comment]
PR is https://github.com/SSSD/sssd-test-suite/pull/12 closing this issue.
