### ISSUE TITLE
'domains' not set correctly in sssd.conf for IPA enrollment

### ISSUE THREAD

**Issue by justin-stephenson** [SSSD/sssd-test-suite#19]
After running the commands here:

https://github.com/SSSD/sssd-test-suite#i-want-to-try-sssd-with-freeipa

The client system is setup with:

~~~
[root@master.client.vm ~]# grep 'domains' /etc/sssd/sssd.conf 
domains = ldap.vm
~~~

This required manual editing to add the `ipa.vm` domain to resolve IPA users.

I am not sure if this issue is reproducible, so I am creating this issue to keep track of it. If it is reproducible I will look into finding a fix when I am able to.

**Comment by pbrezina** [comment]
We can either automate it (which would be possible I guess) or just update the documentation and tell that sssd.conf needs to be updated and sssd restarted.

**Comment by pbrezina** [comment]
I think doc update is enough.
